---
layout: page
title: "Decidable Equality"
category: lemmas functions homotopy
toc: true
agda: true
gallery: true
latex: true
references: true
linkify: true
showcitation: true
home: true
---

<div class="hide" >
<pre class="Agda">
<a id="228" class="Symbol">{-#</a> <a id="232" class="Keyword">OPTIONS</a> <a id="240" class="Pragma">--without-K</a> <a id="252" class="Symbol">#-}</a>
<a id="256" class="Keyword">open</a> <a id="261" class="Keyword">import</a> <a id="268" href="TransportLemmas.html" class="Module">TransportLemmas</a>
<a id="284" class="Keyword">open</a> <a id="289" class="Keyword">import</a> <a id="296" href="EquivalenceType.html" class="Module">EquivalenceType</a>
<a id="312" class="Keyword">open</a> <a id="317" class="Keyword">import</a> <a id="324" href="HomotopyType.html" class="Module">HomotopyType</a>
</pre>
</div>


## Decidable equality

A type has decidable equality if any two of its
elements are equal or different. This would be a particular
instance of the Law of Excluded Middle that holds even if we do not
assume Excluded Middle.

<pre class="Agda">
<a id="594" class="Keyword">module</a> <a id="601" href="DecidableEquality.html" class="Module">DecidableEquality</a> <a id="619" class="Symbol">{</a><a id="620" href="DecidableEquality.html#620" class="Bound">ℓ</a><a id="621" class="Symbol">}</a> <a id="623" class="Keyword">where</a>

  <a id="632" class="Comment">-- A type has decidable equality if we can prove that any two of its</a>
  <a id="703" class="Comment">-- elements are equal or different.</a>
  <a id="decEq"></a><a id="741" href="DecidableEquality.html#741" class="Function">decEq</a> <a id="747" class="Symbol">:</a> <a id="749" class="Symbol">(</a><a id="750" href="DecidableEquality.html#750" class="Bound">A</a> <a id="752" class="Symbol">:</a> <a id="754" href="Intro.html#1442" class="Function">Type</a> <a id="759" href="DecidableEquality.html#620" class="Bound">ℓ</a><a id="760" class="Symbol">)</a> <a id="762" class="Symbol">→</a> <a id="764" href="Intro.html#1442" class="Function">Type</a> <a id="769" href="DecidableEquality.html#620" class="Bound">ℓ</a>
  <a id="773" href="DecidableEquality.html#741" class="Function">decEq</a> <a id="779" href="DecidableEquality.html#779" class="Bound">A</a> <a id="781" class="Symbol">=</a> <a id="783" class="Symbol">(</a><a id="784" href="DecidableEquality.html#784" class="Bound">a</a> <a id="786" href="DecidableEquality.html#786" class="Bound">b</a> <a id="788" class="Symbol">:</a> <a id="790" href="DecidableEquality.html#779" class="Bound">A</a><a id="791" class="Symbol">)</a> <a id="793" class="Symbol">→</a> <a id="795" class="Symbol">(</a><a id="796" href="DecidableEquality.html#784" class="Bound">a</a> <a id="798" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="801" href="DecidableEquality.html#786" class="Bound">b</a><a id="802" class="Symbol">)</a> <a id="804" href="BasicTypes.html#2173" class="Datatype Operator">+</a> <a id="806" href="BasicTypes.html#806" class="Function">¬</a> <a id="808" class="Symbol">(</a><a id="809" href="DecidableEquality.html#784" class="Bound">a</a> <a id="811" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="814" href="DecidableEquality.html#786" class="Bound">b</a><a id="815" class="Symbol">)</a>

  <a id="820" class="Comment">-- The product of types with decidable equality is a type with</a>
  <a id="885" class="Comment">-- decidable equality.</a>
  <a id="decEqProd"></a><a id="910" href="DecidableEquality.html#910" class="Function">decEqProd</a>
    <a id="924" class="Symbol">:</a> <a id="926" class="Symbol">{</a><a id="927" href="DecidableEquality.html#927" class="Bound">A</a> <a id="929" href="DecidableEquality.html#929" class="Bound">B</a> <a id="931" class="Symbol">:</a> <a id="933" href="Intro.html#1442" class="Function">Type</a> <a id="938" href="DecidableEquality.html#620" class="Bound">ℓ</a><a id="939" class="Symbol">}</a>
    <a id="945" class="Symbol">→</a> <a id="947" href="DecidableEquality.html#741" class="Function">decEq</a> <a id="953" href="DecidableEquality.html#927" class="Bound">A</a> <a id="955" class="Symbol">→</a> <a id="957" href="DecidableEquality.html#741" class="Function">decEq</a> <a id="963" href="DecidableEquality.html#929" class="Bound">B</a>
    <a id="969" class="Comment">-------------------</a>
    <a id="993" class="Symbol">→</a> <a id="995" href="DecidableEquality.html#741" class="Function">decEq</a> <a id="1001" class="Symbol">(</a><a id="1002" href="DecidableEquality.html#927" class="Bound">A</a> <a id="1004" href="BasicTypes.html#1956" class="Function Operator">×</a> <a id="1006" href="DecidableEquality.html#929" class="Bound">B</a><a id="1007" class="Symbol">)</a>

  <a id="1012" href="DecidableEquality.html#910" class="Function">decEqProd</a> <a id="1022" href="DecidableEquality.html#1022" class="Bound">da</a> <a id="1025" href="DecidableEquality.html#1025" class="Bound">db</a> <a id="1028" class="Symbol">(</a><a id="1029" href="DecidableEquality.html#1029" class="Bound">a1</a> <a id="1032" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1034" href="DecidableEquality.html#1034" class="Bound">b1</a><a id="1036" class="Symbol">)</a> <a id="1038" class="Symbol">(</a><a id="1039" href="DecidableEquality.html#1039" class="Bound">a2</a> <a id="1042" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1044" href="DecidableEquality.html#1044" class="Bound">b2</a><a id="1046" class="Symbol">)</a> <a id="1048" class="Keyword">with</a> <a id="1053" class="Symbol">(</a><a id="1054" href="DecidableEquality.html#1022" class="Bound">da</a> <a id="1057" href="DecidableEquality.html#1029" class="Bound">a1</a> <a id="1060" href="DecidableEquality.html#1039" class="Bound">a2</a><a id="1062" class="Symbol">)</a> <a id="1064" class="Symbol">|</a> <a id="1066" class="Symbol">(</a><a id="1067" href="DecidableEquality.html#1025" class="Bound">db</a> <a id="1070" href="DecidableEquality.html#1034" class="Bound">b1</a> <a id="1073" href="DecidableEquality.html#1044" class="Bound">b2</a><a id="1075" class="Symbol">)</a>
  <a id="1079" href="DecidableEquality.html#910" class="Function">decEqProd</a> <a id="1089" href="DecidableEquality.html#1089" class="Bound">da</a> <a id="1092" href="DecidableEquality.html#1092" class="Bound">db</a> <a id="1095" class="Symbol">(</a><a id="1096" href="DecidableEquality.html#1096" class="Bound">a1</a> <a id="1099" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1101" href="DecidableEquality.html#1101" class="Bound">b1</a><a id="1103" class="Symbol">)</a> <a id="1105" class="Symbol">(</a><a id="1106" href="DecidableEquality.html#1106" class="Bound">a2</a> <a id="1109" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1111" href="DecidableEquality.html#1111" class="Bound">b2</a><a id="1113" class="Symbol">)</a> <a id="1115" class="Symbol">|</a> <a id="1117" href="BasicTypes.html#2238" class="InductiveConstructor">inl</a> <a id="1121" href="DecidableEquality.html#1121" class="Bound">aeq</a> <a id="1125" class="Symbol">|</a> <a id="1127" href="BasicTypes.html#2238" class="InductiveConstructor">inl</a> <a id="1131" href="DecidableEquality.html#1131" class="Bound">beq</a> <a id="1135" class="Symbol">=</a> <a id="1137" href="BasicTypes.html#2238" class="InductiveConstructor">inl</a> <a id="1141" class="Symbol">(</a><a id="1142" href="TransportLemmas.html#10740" class="Function">prodByComponents</a> <a id="1159" class="Symbol">(</a><a id="1160" href="DecidableEquality.html#1121" class="Bound">aeq</a> <a id="1164" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1166" href="DecidableEquality.html#1131" class="Bound">beq</a><a id="1169" class="Symbol">))</a>
  <a id="1174" href="DecidableEquality.html#910" class="Function">decEqProd</a> <a id="1184" href="DecidableEquality.html#1184" class="Bound">da</a> <a id="1187" href="DecidableEquality.html#1187" class="Bound">db</a> <a id="1190" class="Symbol">(</a><a id="1191" href="DecidableEquality.html#1191" class="Bound">a1</a> <a id="1194" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1196" href="DecidableEquality.html#1196" class="Bound">b1</a><a id="1198" class="Symbol">)</a> <a id="1200" class="Symbol">(</a><a id="1201" href="DecidableEquality.html#1201" class="Bound">a2</a> <a id="1204" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1206" href="DecidableEquality.html#1206" class="Bound">b2</a><a id="1208" class="Symbol">)</a> <a id="1210" class="Symbol">|</a> <a id="1212" href="BasicTypes.html#2238" class="InductiveConstructor">inl</a> <a id="1216" href="DecidableEquality.html#1216" class="Bound">aeq</a> <a id="1220" class="Symbol">|</a> <a id="1222" href="BasicTypes.html#2256" class="InductiveConstructor">inr</a> <a id="1226" href="DecidableEquality.html#1226" class="Bound">bnq</a> <a id="1230" class="Symbol">=</a> <a id="1232" href="BasicTypes.html#2256" class="InductiveConstructor">inr</a> <a id="1236" class="Symbol">λ</a> <a id="1238" href="DecidableEquality.html#1238" class="Bound">b</a> <a id="1240" class="Symbol">→</a> <a id="1242" href="DecidableEquality.html#1226" class="Bound">bnq</a> <a id="1246" class="Symbol">(</a><a id="1247" href="AlgebraOnPaths.html#454" class="Function">ap</a> <a id="1250" href="BasicTypes.html#1506" class="Field">π₂</a> <a id="1253" href="DecidableEquality.html#1238" class="Bound">b</a><a id="1254" class="Symbol">)</a>
  <a id="1258" href="DecidableEquality.html#910" class="Function">decEqProd</a> <a id="1268" href="DecidableEquality.html#1268" class="Bound">da</a> <a id="1271" href="DecidableEquality.html#1271" class="Bound">db</a> <a id="1274" class="Symbol">(</a><a id="1275" href="DecidableEquality.html#1275" class="Bound">a1</a> <a id="1278" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1280" href="DecidableEquality.html#1280" class="Bound">b1</a><a id="1282" class="Symbol">)</a> <a id="1284" class="Symbol">(</a><a id="1285" href="DecidableEquality.html#1285" class="Bound">a2</a> <a id="1288" href="BasicTypes.html#1479" class="InductiveConstructor Operator">,</a> <a id="1290" href="DecidableEquality.html#1290" class="Bound">b2</a><a id="1292" class="Symbol">)</a> <a id="1294" class="Symbol">|</a> <a id="1296" href="BasicTypes.html#2256" class="InductiveConstructor">inr</a> <a id="1300" href="DecidableEquality.html#1300" class="Bound">anq</a> <a id="1304" class="Symbol">|</a> <a id="1306" href="DecidableEquality.html#1306" class="Bound">u</a>       <a id="1314" class="Symbol">=</a> <a id="1316" href="BasicTypes.html#2256" class="InductiveConstructor">inr</a> <a id="1320" class="Symbol">λ</a> <a id="1322" href="DecidableEquality.html#1322" class="Bound">b</a> <a id="1324" class="Symbol">→</a> <a id="1326" href="DecidableEquality.html#1300" class="Bound">anq</a> <a id="1330" class="Symbol">(</a><a id="1331" href="AlgebraOnPaths.html#454" class="Function">ap</a> <a id="1334" href="BasicTypes.html#1495" class="Field">π₁</a> <a id="1337" href="DecidableEquality.html#1322" class="Bound">b</a><a id="1338" class="Symbol">)</a>
</pre>
