---
layout: page
title: "Fundamental Group Type"
toc: true
agda: true
gallery: true
latex: true
references: true
linkify: true
showcitation: true
home: true
---


<div class="hide" >
<pre class="Agda">
<a id="197" class="Symbol">{-#</a> <a id="201" class="Keyword">OPTIONS</a> <a id="209" class="Pragma">--without-K</a> <a id="221" class="Symbol">#-}</a>
<a id="225" class="Keyword">open</a> <a id="230" class="Keyword">import</a> <a id="237" href="TransportLemmas.html" class="Module">TransportLemmas</a>
<a id="253" class="Keyword">open</a> <a id="258" class="Keyword">import</a> <a id="265" href="EquivalenceType.html" class="Module">EquivalenceType</a>

<a id="282" class="Keyword">open</a> <a id="287" class="Keyword">import</a> <a id="294" href="HomotopyType.html" class="Module">HomotopyType</a>
<a id="307" class="Keyword">open</a> <a id="312" class="Keyword">import</a> <a id="319" href="FunExtAxiom.html" class="Module">FunExtAxiom</a>
<a id="331" class="Keyword">open</a> <a id="336" class="Keyword">import</a> <a id="343" href="HLevelTypes.html" class="Module">HLevelTypes</a>
<a id="355" class="Keyword">open</a> <a id="360" class="Keyword">import</a> <a id="367" href="CircleType.html" class="Module">CircleType</a>
<a id="378" class="Keyword">open</a> <a id="383" class="Keyword">import</a> <a id="390" href="GroupType.html" class="Module">GroupType</a>
</pre>
</div>

## Fundamental group

Definition of the fundamental group of a type.
Let a:A be one point of the type. The fundamental group on a is the
group given by proofs of the equality (a=a).

<pre class="Agda">
<a id="615" class="Keyword">module</a> <a id="622" href="FundamentalGroupType.html" class="Module">FundamentalGroupType</a> <a id="643" class="Keyword">where</a>

  <a id="652" class="Comment">-- Definition of the fundamental group.</a>
  <a id="Ω"></a><a id="694" href="FundamentalGroupType.html#694" class="Function">Ω</a> <a id="696" class="Symbol">:</a> <a id="698" class="Symbol">∀</a> <a id="700" class="Symbol">{</a><a id="701" href="FundamentalGroupType.html#701" class="Bound">ℓ</a><a id="702" class="Symbol">}</a> <a id="704" class="Symbol">(</a><a id="705" href="FundamentalGroupType.html#705" class="Bound">A</a> <a id="707" class="Symbol">:</a> <a id="709" href="Intro.html#1442" class="Function">Type</a> <a id="714" href="FundamentalGroupType.html#701" class="Bound">ℓ</a><a id="715" class="Symbol">)</a> <a id="717" class="Symbol">→</a> <a id="719" class="Symbol">(</a><a id="720" href="FundamentalGroupType.html#720" class="Bound">a</a> <a id="722" class="Symbol">:</a> <a id="724" href="FundamentalGroupType.html#705" class="Bound">A</a><a id="725" class="Symbol">)</a> <a id="727" class="Symbol">→</a> <a id="729" href="Intro.html#1442" class="Function">Type</a> <a id="734" href="FundamentalGroupType.html#701" class="Bound">ℓ</a>
  <a id="738" href="FundamentalGroupType.html#694" class="Function">Ω</a> <a id="740" href="FundamentalGroupType.html#740" class="Bound">A</a> <a id="742" href="FundamentalGroupType.html#742" class="Bound">a</a> <a id="744" class="Symbol">=</a> <a id="746" class="Symbol">(</a><a id="747" href="FundamentalGroupType.html#742" class="Bound">a</a> <a id="749" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="752" href="FundamentalGroupType.html#742" class="Bound">a</a><a id="753" class="Symbol">)</a>

  <a id="758" class="Comment">-- Its group structure.</a>
  <a id="Ω-st"></a><a id="784" href="FundamentalGroupType.html#784" class="Function">Ω-st</a> <a id="789" class="Symbol">:</a> <a id="791" class="Symbol">∀</a> <a id="793" class="Symbol">{</a><a id="794" href="FundamentalGroupType.html#794" class="Bound">ℓ</a><a id="795" class="Symbol">}</a> <a id="797" class="Symbol">(</a><a id="798" href="FundamentalGroupType.html#798" class="Bound">A</a> <a id="800" class="Symbol">:</a> <a id="802" href="Intro.html#1442" class="Function">Type</a> <a id="807" href="FundamentalGroupType.html#794" class="Bound">ℓ</a><a id="808" class="Symbol">)</a> <a id="810" class="Symbol">→</a> <a id="812" class="Symbol">(</a><a id="813" href="FundamentalGroupType.html#813" class="Bound">a</a> <a id="815" class="Symbol">:</a> <a id="817" href="FundamentalGroupType.html#798" class="Bound">A</a><a id="818" class="Symbol">)</a> <a id="820" class="Symbol">→</a> <a id="822" href="GroupType.html#406" class="Record">GroupStructure</a> <a id="837" class="Symbol">(</a><a id="838" href="FundamentalGroupType.html#694" class="Function">Ω</a> <a id="840" href="FundamentalGroupType.html#798" class="Bound">A</a> <a id="842" href="FundamentalGroupType.html#813" class="Bound">a</a><a id="843" class="Symbol">)</a>
  <a id="847" href="FundamentalGroupType.html#784" class="Function">Ω-st</a> <a id="852" href="FundamentalGroupType.html#852" class="Bound">A</a> <a id="854" href="FundamentalGroupType.html#854" class="Bound">a</a> <a id="856" class="Symbol">=</a> <a id="858" href="GroupType.html#469" class="InductiveConstructor">group-structure</a> <a id="874" href="EqualityType.html#2151" class="Function Operator">_·_</a> <a id="878" class="Symbol">(</a><a id="879" href="EqualityType.html#1111" class="Function">refl</a> <a id="884" href="FundamentalGroupType.html#854" class="Bound">a</a><a id="885" class="Symbol">)</a>
    <a id="891" class="Symbol">(λ</a> <a id="894" href="FundamentalGroupType.html#894" class="Bound">a</a> <a id="896" class="Symbol">→</a> <a id="898" href="EqualityType.html#2412" class="Function">inv</a> <a id="902" class="Symbol">(</a><a id="903" href="AlgebraOnPaths.html#2908" class="Function">·-lunit</a> <a id="911" href="FundamentalGroupType.html#894" class="Bound">a</a><a id="912" class="Symbol">))</a> <a id="915" class="Symbol">(λ</a> <a id="918" href="FundamentalGroupType.html#918" class="Bound">a</a> <a id="920" class="Symbol">→</a> <a id="922" href="EqualityType.html#2412" class="Function">inv</a> <a id="926" class="Symbol">(</a><a id="927" href="AlgebraOnPaths.html#2747" class="Function">·-runit</a> <a id="935" href="FundamentalGroupType.html#918" class="Bound">a</a><a id="936" class="Symbol">))</a>
    <a id="943" class="Symbol">(λ</a> <a id="946" href="FundamentalGroupType.html#946" class="Bound">x</a> <a id="948" href="FundamentalGroupType.html#948" class="Bound">y</a> <a id="950" href="FundamentalGroupType.html#950" class="Bound">z</a> <a id="952" class="Symbol">→</a> <a id="954" href="EqualityType.html#2412" class="Function">inv</a> <a id="958" class="Symbol">(</a><a id="959" href="AlgebraOnPaths.html#3569" class="Function">·-assoc</a> <a id="967" href="FundamentalGroupType.html#946" class="Bound">x</a> <a id="969" href="FundamentalGroupType.html#948" class="Bound">y</a> <a id="971" href="FundamentalGroupType.html#950" class="Bound">z</a><a id="972" class="Symbol">))</a>
    <a id="979" href="EqualityType.html#2412" class="Function">inv</a> <a id="983" href="AlgebraOnPaths.html#3232" class="Function">·-rinv</a> <a id="990" href="AlgebraOnPaths.html#3069" class="Function">·-linv</a>

  <a id="Ω-gr"></a><a id="1000" href="FundamentalGroupType.html#1000" class="Function">Ω-gr</a> <a id="1005" class="Symbol">:</a> <a id="1007" class="Symbol">∀</a> <a id="1009" class="Symbol">{</a><a id="1010" href="FundamentalGroupType.html#1010" class="Bound">ℓ</a><a id="1011" class="Symbol">}</a> <a id="1013" class="Symbol">(</a><a id="1014" href="FundamentalGroupType.html#1014" class="Bound">A</a> <a id="1016" class="Symbol">:</a> <a id="1018" href="Intro.html#1442" class="Function">Type</a> <a id="1023" href="FundamentalGroupType.html#1010" class="Bound">ℓ</a><a id="1024" class="Symbol">)</a> <a id="1026" class="Symbol">→</a> <a id="1028" class="Symbol">(</a><a id="1029" href="FundamentalGroupType.html#1029" class="Bound">a</a> <a id="1031" class="Symbol">:</a> <a id="1033" href="FundamentalGroupType.html#1014" class="Bound">A</a><a id="1034" class="Symbol">)</a> <a id="1036" class="Symbol">→</a> <a id="1038" href="GroupType.html#815" class="Record">Group</a> <a id="1044" class="Symbol">{</a><a id="1045" href="FundamentalGroupType.html#1010" class="Bound">ℓ</a><a id="1046" class="Symbol">}</a>
  <a id="1050" href="FundamentalGroupType.html#1000" class="Function">Ω-gr</a> <a id="1055" href="FundamentalGroupType.html#1055" class="Bound">A</a> <a id="1057" href="FundamentalGroupType.html#1057" class="Bound">a</a> <a id="1059" class="Symbol">=</a> <a id="1061" href="GroupType.html#863" class="InductiveConstructor">group</a> <a id="1067" class="Symbol">(</a><a id="1068" href="FundamentalGroupType.html#1057" class="Bound">a</a> <a id="1070" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="1073" href="FundamentalGroupType.html#1057" class="Bound">a</a><a id="1074" class="Symbol">)</a> <a id="1076" class="Symbol">(</a><a id="1077" href="FundamentalGroupType.html#784" class="Function">Ω-st</a> <a id="1082" href="FundamentalGroupType.html#1055" class="Bound">A</a> <a id="1084" href="FundamentalGroupType.html#1057" class="Bound">a</a><a id="1085" class="Symbol">)</a>

  <a id="Ω-st-r"></a><a id="1090" href="FundamentalGroupType.html#1090" class="Function">Ω-st-r</a> <a id="1097" class="Symbol">:</a> <a id="1099" class="Symbol">∀</a> <a id="1101" class="Symbol">{</a><a id="1102" href="FundamentalGroupType.html#1102" class="Bound">ℓ</a><a id="1103" class="Symbol">}</a> <a id="1105" class="Symbol">(</a><a id="1106" href="FundamentalGroupType.html#1106" class="Bound">A</a> <a id="1108" class="Symbol">:</a> <a id="1110" href="Intro.html#1442" class="Function">Type</a> <a id="1115" href="FundamentalGroupType.html#1102" class="Bound">ℓ</a><a id="1116" class="Symbol">)</a> <a id="1118" class="Symbol">→</a> <a id="1120" class="Symbol">(</a><a id="1121" href="FundamentalGroupType.html#1121" class="Bound">a</a> <a id="1123" class="Symbol">:</a> <a id="1125" href="FundamentalGroupType.html#1106" class="Bound">A</a><a id="1126" class="Symbol">)</a> <a id="1128" class="Symbol">→</a> <a id="1130" href="GroupType.html#406" class="Record">GroupStructure</a> <a id="1145" class="Symbol">(</a><a id="1146" href="FundamentalGroupType.html#694" class="Function">Ω</a> <a id="1148" href="FundamentalGroupType.html#1106" class="Bound">A</a> <a id="1150" href="FundamentalGroupType.html#1121" class="Bound">a</a><a id="1151" class="Symbol">)</a>
  <a id="1155" href="FundamentalGroupType.html#1090" class="Function">Ω-st-r</a> <a id="1162" href="FundamentalGroupType.html#1162" class="Bound">A</a> <a id="1164" href="FundamentalGroupType.html#1164" class="Bound">a</a> <a id="1166" class="Symbol">=</a> <a id="1168" href="GroupType.html#469" class="InductiveConstructor">group-structure</a> <a id="1184" class="Symbol">(λ</a> <a id="1187" href="FundamentalGroupType.html#1187" class="Bound">x</a> <a id="1189" href="FundamentalGroupType.html#1189" class="Bound">y</a> <a id="1191" class="Symbol">→</a> <a id="1193" href="FundamentalGroupType.html#1189" class="Bound">y</a> <a id="1195" href="EqualityType.html#2151" class="Function Operator">·</a> <a id="1197" href="FundamentalGroupType.html#1187" class="Bound">x</a><a id="1198" class="Symbol">)</a> <a id="1200" class="Symbol">(</a><a id="1201" href="EqualityType.html#1111" class="Function">refl</a> <a id="1206" href="FundamentalGroupType.html#1164" class="Bound">a</a><a id="1207" class="Symbol">)</a>
    <a id="1213" class="Symbol">(λ</a> <a id="1216" href="FundamentalGroupType.html#1216" class="Bound">a</a> <a id="1218" class="Symbol">→</a> <a id="1220" href="EqualityType.html#2412" class="Function">inv</a> <a id="1224" class="Symbol">(</a><a id="1225" href="AlgebraOnPaths.html#2747" class="Function">·-runit</a> <a id="1233" href="FundamentalGroupType.html#1216" class="Bound">a</a><a id="1234" class="Symbol">))</a> <a id="1237" class="Symbol">(λ</a> <a id="1240" href="FundamentalGroupType.html#1240" class="Bound">a</a> <a id="1242" class="Symbol">→</a> <a id="1244" href="EqualityType.html#2412" class="Function">inv</a> <a id="1248" class="Symbol">(</a><a id="1249" href="AlgebraOnPaths.html#2908" class="Function">·-lunit</a> <a id="1257" href="FundamentalGroupType.html#1240" class="Bound">a</a><a id="1258" class="Symbol">))</a>
    <a id="1265" class="Symbol">(λ</a> <a id="1268" href="FundamentalGroupType.html#1268" class="Bound">x</a> <a id="1270" href="FundamentalGroupType.html#1270" class="Bound">y</a> <a id="1272" href="FundamentalGroupType.html#1272" class="Bound">z</a> <a id="1274" class="Symbol">→</a> <a id="1276" href="AlgebraOnPaths.html#3569" class="Function">·-assoc</a> <a id="1284" href="FundamentalGroupType.html#1272" class="Bound">z</a> <a id="1286" href="FundamentalGroupType.html#1270" class="Bound">y</a> <a id="1288" href="FundamentalGroupType.html#1268" class="Bound">x</a><a id="1289" class="Symbol">)</a>
    <a id="1295" href="EqualityType.html#2412" class="Function">inv</a> <a id="1299" href="AlgebraOnPaths.html#3069" class="Function">·-linv</a> <a id="1306" href="AlgebraOnPaths.html#3232" class="Function">·-rinv</a>
</pre>
