---
layout: page
title: "Function extensionality and Transport"
category: lemmas functions homotopy
toc: true
agda: true
gallery: true
latex: true
references: true
linkify: true
showcitation: true
home: true
---

<div class="hide" >
<pre class="Agda">
<a id="247" class="Symbol">{-#</a> <a id="251" class="Keyword">OPTIONS</a> <a id="259" class="Pragma">--without-K</a> <a id="271" class="Symbol">#-}</a>
<a id="275" class="Keyword">open</a> <a id="280" class="Keyword">import</a> <a id="287" href="Transport.html" class="Module">Transport</a>
<a id="297" class="Keyword">open</a> <a id="302" class="Keyword">import</a> <a id="309" href="EquivalenceType.html" class="Module">EquivalenceType</a>
<a id="325" class="Keyword">open</a> <a id="330" class="Keyword">import</a> <a id="337" href="FunExtAxiom.html" class="Module">FunExtAxiom</a>
</pre>
</div>

Function extensionality in the transport case

<pre class="Agda">
<a id="428" class="Keyword">module</a> <a id="435" href="FunExtTransport.html" class="Module">FunExtTransport</a>
  <a id="453" class="Symbol">{</a><a id="454" href="FunExtTransport.html#454" class="Bound">ℓᵢ</a> <a id="457" href="FunExtTransport.html#457" class="Bound">ℓⱼ</a><a id="459" class="Symbol">}</a> <a id="461" class="Symbol">{</a><a id="462" href="FunExtTransport.html#462" class="Bound">X</a> <a id="464" class="Symbol">:</a> <a id="466" href="Intro.html#1442" class="Function">Type</a> <a id="471" href="FunExtTransport.html#454" class="Bound">ℓᵢ</a><a id="473" class="Symbol">}</a> <a id="475" class="Symbol">{</a><a id="476" href="FunExtTransport.html#476" class="Bound">A</a> <a id="478" href="FunExtTransport.html#478" class="Bound">B</a> <a id="480" class="Symbol">:</a> <a id="482" href="FunExtTransport.html#462" class="Bound">X</a> <a id="484" class="Symbol">→</a> <a id="486" href="Intro.html#1442" class="Function">Type</a> <a id="491" href="FunExtTransport.html#457" class="Bound">ℓⱼ</a><a id="493" class="Symbol">}</a> <a id="495" class="Symbol">{</a><a id="496" href="FunExtTransport.html#496" class="Bound">x</a> <a id="498" href="FunExtTransport.html#498" class="Bound">y</a> <a id="500" class="Symbol">:</a> <a id="502" href="FunExtTransport.html#462" class="Bound">X</a><a id="503" class="Symbol">}</a> <a id="505" class="Keyword">where</a>
</pre>

<pre class="Agda">
  <a id="funext-transport"></a><a id="538" href="FunExtTransport.html#538" class="Function">funext-transport</a>
    <a id="559" class="Symbol">:</a> <a id="561" class="Symbol">(</a><a id="562" href="FunExtTransport.html#562" class="Bound">p</a> <a id="564" class="Symbol">:</a> <a id="566" href="FunExtTransport.html#496" class="Bound">x</a> <a id="568" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="571" href="FunExtTransport.html#498" class="Bound">y</a><a id="572" class="Symbol">)</a> <a id="574" class="Symbol">→</a> <a id="576" class="Symbol">(</a><a id="577" href="FunExtTransport.html#577" class="Bound">f</a> <a id="579" class="Symbol">:</a> <a id="581" href="FunExtTransport.html#476" class="Bound">A</a> <a id="583" href="FunExtTransport.html#496" class="Bound">x</a> <a id="585" class="Symbol">→</a> <a id="587" href="FunExtTransport.html#478" class="Bound">B</a> <a id="589" href="FunExtTransport.html#496" class="Bound">x</a><a id="590" class="Symbol">)</a> <a id="592" class="Symbol">→</a> <a id="594" class="Symbol">(</a><a id="595" href="FunExtTransport.html#595" class="Bound">g</a> <a id="597" class="Symbol">:</a> <a id="599" href="FunExtTransport.html#476" class="Bound">A</a> <a id="601" href="FunExtTransport.html#498" class="Bound">y</a> <a id="603" class="Symbol">→</a> <a id="605" href="FunExtTransport.html#478" class="Bound">B</a> <a id="607" href="FunExtTransport.html#498" class="Bound">y</a><a id="608" class="Symbol">)</a>
    <a id="614" class="Comment">------------------------------------------------------------</a>
    <a id="679" class="Symbol">→</a> <a id="681" class="Symbol">((</a><a id="683" href="FunExtTransport.html#562" class="Bound">p</a> <a id="685" href="Transport.html#799" class="Function Operator">✶</a><a id="686" class="Symbol">)</a> <a id="688" href="FunExtTransport.html#577" class="Bound">f</a> <a id="690" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="693" href="FunExtTransport.html#595" class="Bound">g</a><a id="694" class="Symbol">)</a> <a id="696" href="EquivalenceType.html#778" class="Function Operator">≃</a> <a id="698" class="Symbol">((</a><a id="700" href="FunExtTransport.html#700" class="Bound">a</a> <a id="702" class="Symbol">:</a> <a id="704" href="FunExtTransport.html#476" class="Bound">A</a><a id="705" class="Symbol">(</a><a id="706" href="FunExtTransport.html#496" class="Bound">x</a><a id="707" class="Symbol">))</a> <a id="710" class="Symbol">→</a> <a id="712" class="Symbol">(</a><a id="713" href="FunExtTransport.html#562" class="Bound">p</a> <a id="715" href="Transport.html#799" class="Function Operator">✶</a><a id="716" class="Symbol">)</a> <a id="718" class="Symbol">(</a><a id="719" href="FunExtTransport.html#577" class="Bound">f</a> <a id="721" href="FunExtTransport.html#700" class="Bound">a</a><a id="722" class="Symbol">)</a> <a id="724" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="727" href="FunExtTransport.html#595" class="Bound">g</a> <a id="729" class="Symbol">((</a><a id="731" href="FunExtTransport.html#562" class="Bound">p</a> <a id="733" href="Transport.html#799" class="Function Operator">✶</a><a id="734" class="Symbol">)</a> <a id="736" href="FunExtTransport.html#700" class="Bound">a</a><a id="737" class="Symbol">))</a>

  <a id="743" href="FunExtTransport.html#538" class="Function">funext-transport</a> <a id="760" href="EqualityType.html#985" class="InductiveConstructor">idp</a> <a id="764" href="FunExtTransport.html#764" class="Bound">f</a> <a id="766" href="FunExtTransport.html#766" class="Bound">g</a> <a id="768" class="Symbol">=</a> <a id="770" href="FunExtAxiom.html#749" class="Function">eqFunExt</a>
</pre>

<pre class="Agda">
  <a id="funext-transport-l"></a><a id="806" href="FunExtTransport.html#806" class="Function">funext-transport-l</a>
    <a id="829" class="Symbol">:</a> <a id="831" class="Symbol">(</a><a id="832" href="FunExtTransport.html#832" class="Bound">p</a> <a id="834" class="Symbol">:</a> <a id="836" href="FunExtTransport.html#496" class="Bound">x</a> <a id="838" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="841" href="FunExtTransport.html#498" class="Bound">y</a><a id="842" class="Symbol">)</a>
    <a id="848" class="Symbol">→</a> <a id="850" class="Symbol">(</a><a id="851" href="FunExtTransport.html#851" class="Bound">f</a> <a id="853" class="Symbol">:</a> <a id="855" href="FunExtTransport.html#476" class="Bound">A</a> <a id="857" href="FunExtTransport.html#496" class="Bound">x</a> <a id="859" class="Symbol">→</a> <a id="861" href="FunExtTransport.html#478" class="Bound">B</a> <a id="863" href="FunExtTransport.html#496" class="Bound">x</a><a id="864" class="Symbol">)</a>
    <a id="870" class="Symbol">→</a> <a id="872" class="Symbol">(</a><a id="873" href="FunExtTransport.html#873" class="Bound">g</a> <a id="875" class="Symbol">:</a> <a id="877" href="FunExtTransport.html#476" class="Bound">A</a> <a id="879" href="FunExtTransport.html#498" class="Bound">y</a> <a id="881" class="Symbol">→</a> <a id="883" href="FunExtTransport.html#478" class="Bound">B</a> <a id="885" href="FunExtTransport.html#498" class="Bound">y</a><a id="886" class="Symbol">)</a>
    <a id="892" class="Symbol">→</a> <a id="894" class="Symbol">((</a><a id="896" href="FunExtTransport.html#832" class="Bound">p</a> <a id="898" href="Transport.html#799" class="Function Operator">✶</a><a id="899" class="Symbol">)</a> <a id="901" href="FunExtTransport.html#851" class="Bound">f</a> <a id="903" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="906" href="FunExtTransport.html#873" class="Bound">g</a><a id="907" class="Symbol">)</a>
    <a id="913" class="Comment">-------------------------------------------</a>
    <a id="961" class="Symbol">→</a> <a id="963" class="Symbol">((</a><a id="965" href="FunExtTransport.html#965" class="Bound">a</a> <a id="967" class="Symbol">:</a> <a id="969" href="FunExtTransport.html#476" class="Bound">A</a><a id="970" class="Symbol">(</a><a id="971" href="FunExtTransport.html#496" class="Bound">x</a><a id="972" class="Symbol">))</a> <a id="975" class="Symbol">→</a> <a id="977" class="Symbol">(</a><a id="978" href="FunExtTransport.html#832" class="Bound">p</a> <a id="980" href="Transport.html#799" class="Function Operator">✶</a><a id="981" class="Symbol">)</a> <a id="983" class="Symbol">(</a><a id="984" href="FunExtTransport.html#851" class="Bound">f</a> <a id="986" href="FunExtTransport.html#965" class="Bound">a</a><a id="987" class="Symbol">)</a> <a id="989" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="992" href="FunExtTransport.html#873" class="Bound">g</a> <a id="994" class="Symbol">((</a><a id="996" href="FunExtTransport.html#832" class="Bound">p</a> <a id="998" href="Transport.html#799" class="Function Operator">✶</a><a id="999" class="Symbol">)</a> <a id="1001" href="FunExtTransport.html#965" class="Bound">a</a><a id="1002" class="Symbol">))</a>

  <a id="1008" href="FunExtTransport.html#806" class="Function">funext-transport-l</a> <a id="1027" href="FunExtTransport.html#1027" class="Bound">p</a> <a id="1029" href="FunExtTransport.html#1029" class="Bound">f</a> <a id="1031" href="FunExtTransport.html#1031" class="Bound">g</a> <a id="1033" class="Symbol">=</a> <a id="1035" href="EquivalenceType.html#995" class="Function">lemap</a> <a id="1041" class="Symbol">(</a><a id="1042" href="FunExtTransport.html#538" class="Function">funext-transport</a> <a id="1059" href="FunExtTransport.html#1027" class="Bound">p</a> <a id="1061" class="Symbol">_</a> <a id="1063" class="Symbol">_)</a>
</pre>

<pre class="Agda">
  <a id="funext-transport-r"></a><a id="1093" href="FunExtTransport.html#1093" class="Function">funext-transport-r</a>
    <a id="1116" class="Symbol">:</a> <a id="1118" class="Symbol">(</a><a id="1119" href="FunExtTransport.html#1119" class="Bound">p</a> <a id="1121" class="Symbol">:</a> <a id="1123" href="FunExtTransport.html#496" class="Bound">x</a> <a id="1125" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="1128" href="FunExtTransport.html#498" class="Bound">y</a><a id="1129" class="Symbol">)</a>
    <a id="1135" class="Symbol">→</a> <a id="1137" class="Symbol">(</a><a id="1138" href="FunExtTransport.html#1138" class="Bound">f</a> <a id="1140" class="Symbol">:</a> <a id="1142" href="FunExtTransport.html#476" class="Bound">A</a> <a id="1144" href="FunExtTransport.html#496" class="Bound">x</a> <a id="1146" class="Symbol">→</a> <a id="1148" href="FunExtTransport.html#478" class="Bound">B</a> <a id="1150" href="FunExtTransport.html#496" class="Bound">x</a><a id="1151" class="Symbol">)</a>
    <a id="1157" class="Symbol">→</a> <a id="1159" class="Symbol">(</a><a id="1160" href="FunExtTransport.html#1160" class="Bound">g</a> <a id="1162" class="Symbol">:</a> <a id="1164" href="FunExtTransport.html#476" class="Bound">A</a> <a id="1166" href="FunExtTransport.html#498" class="Bound">y</a> <a id="1168" class="Symbol">→</a> <a id="1170" href="FunExtTransport.html#478" class="Bound">B</a> <a id="1172" href="FunExtTransport.html#498" class="Bound">y</a><a id="1173" class="Symbol">)</a>
    <a id="1179" class="Symbol">→</a> <a id="1181" class="Symbol">((</a><a id="1183" href="FunExtTransport.html#1183" class="Bound">a</a> <a id="1185" class="Symbol">:</a> <a id="1187" href="FunExtTransport.html#476" class="Bound">A</a><a id="1188" class="Symbol">(</a><a id="1189" href="FunExtTransport.html#496" class="Bound">x</a><a id="1190" class="Symbol">))</a> <a id="1193" class="Symbol">→</a> <a id="1195" class="Symbol">(</a><a id="1196" href="FunExtTransport.html#1119" class="Bound">p</a> <a id="1198" href="Transport.html#799" class="Function Operator">✶</a><a id="1199" class="Symbol">)</a> <a id="1201" class="Symbol">(</a><a id="1202" href="FunExtTransport.html#1138" class="Bound">f</a> <a id="1204" href="FunExtTransport.html#1183" class="Bound">a</a><a id="1205" class="Symbol">)</a> <a id="1207" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="1210" href="FunExtTransport.html#1160" class="Bound">g</a> <a id="1212" class="Symbol">((</a><a id="1214" href="FunExtTransport.html#1119" class="Bound">p</a> <a id="1216" href="Transport.html#799" class="Function Operator">✶</a><a id="1217" class="Symbol">)</a> <a id="1219" href="FunExtTransport.html#1183" class="Bound">a</a><a id="1220" class="Symbol">))</a>
    <a id="1227" class="Comment">-------------------------------------------</a>
    <a id="1275" class="Symbol">→</a> <a id="1277" class="Symbol">((</a><a id="1279" href="FunExtTransport.html#1119" class="Bound">p</a> <a id="1281" href="Transport.html#799" class="Function Operator">✶</a><a id="1282" class="Symbol">)</a> <a id="1284" href="FunExtTransport.html#1138" class="Bound">f</a> <a id="1286" href="EqualityType.html#931" class="Datatype Operator">==</a> <a id="1289" href="FunExtTransport.html#1160" class="Bound">g</a><a id="1290" class="Symbol">)</a>

  <a id="1295" href="FunExtTransport.html#1093" class="Function">funext-transport-r</a> <a id="1314" href="FunExtTransport.html#1314" class="Bound">p</a> <a id="1316" href="FunExtTransport.html#1316" class="Bound">f</a> <a id="1318" href="FunExtTransport.html#1318" class="Bound">g</a> <a id="1320" class="Symbol">=</a> <a id="1322" href="EquivalenceType.html#1147" class="Function">remap</a> <a id="1328" class="Symbol">(</a><a id="1329" href="FunExtTransport.html#538" class="Function">funext-transport</a> <a id="1346" href="FunExtTransport.html#1314" class="Bound">p</a> <a id="1348" class="Symbol">_</a> <a id="1350" class="Symbol">_)</a>
</pre>
